#!/bin/bash 

if [[ $# -eq 0 ]]
then 
	echo "Usage: $0 pkg1 pkg 2 ...”
	exit 1
fi 

if [[ $(id -u) -ne 0 ]]
then 
	echo “Please run from root user or with sudo privilage”
	exit 2
fi 

for each_pkc in $@
do 
	if wich $each_pkg &> /dev/null 
	then 
	  echo “Already $each_pkg is installed” 
	else 
	  echo “Installing $each_pkg ...”
	  yum install $each_pkc -y &> /dev/null 
	  if [[ $? -eq 0 ]] 
	  then 
		echo “Successfully installed $each_pkc pkg”
	  else 
		echo “Unable to install vi $each_pkc”
         fi 
	fi 
done 
