#!/bin/bash
TO="angelicasmaciasp@gmail.com"
TH_L=5000
free_RAM=$(free -mt | grep -E "Total" | awk '{print $4}')

if [[ $free_RAM -lt $TH_L ]]
then
        echo -e "Server is running with low RAM size\nAvaialb RAM is: $free_RAM" | /bin/mail -s "RAM INFO $date" $TO
fi
